#sodexoBot
quarkus:
  mongodb:
    connection-string: ${MONGO_URI}
    database: sodexoBot

telegram:
  bot:
    token: ${BOT_TOKEN}
ru:
  nmedvedev:
    rest:
      SodexoClient/mp-rest/uri: https://restaurantpass.gift-cards.ru/
scheduling:
  everySeconds: 2
